/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.grupo6.mc1.proyecto1.InterfazGrafica;

import com.grupo6.mc1.proyecto1.LectorArchivosXML;
import java.awt.Color;
import java.awt.GridLayout;
import java.io.File;
import java.util.Arrays;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author usuario
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form CargarArchivos
     */
    public PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaSeleccionarArchivo = new javax.swing.JDialog();
        SelectorArchivo = new javax.swing.JFileChooser();
        PanelOperaciones = new javax.swing.JPanel();
        BtnCalcularMapa = new javax.swing.JButton();
        ScrollMapa = new javax.swing.JScrollPane();
        PanelMapa = new javax.swing.JPanel();
        BarraMenus = new javax.swing.JMenuBar();
        MenuAbrir = new javax.swing.JMenu();
        ItemAbrir = new javax.swing.JMenuItem();
        MenuEditar = new javax.swing.JMenu();

        VentanaSeleccionarArchivo.setSize(new java.awt.Dimension(600, 400));

        SelectorArchivo.setAcceptAllFileFilterUsed(false);
        SelectorArchivo.setFileFilter(new FileNameExtensionFilter("Archivos XML (*.xml)", "xml"));

        javax.swing.GroupLayout VentanaSeleccionarArchivoLayout = new javax.swing.GroupLayout(VentanaSeleccionarArchivo.getContentPane());
        VentanaSeleccionarArchivo.getContentPane().setLayout(VentanaSeleccionarArchivoLayout);
        VentanaSeleccionarArchivoLayout.setHorizontalGroup(
            VentanaSeleccionarArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(VentanaSeleccionarArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(SelectorArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE))
        );
        VentanaSeleccionarArchivoLayout.setVerticalGroup(
            VentanaSeleccionarArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(VentanaSeleccionarArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(SelectorArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnCalcularMapa.setText("Calcular Mapa");

        javax.swing.GroupLayout PanelOperacionesLayout = new javax.swing.GroupLayout(PanelOperaciones);
        PanelOperaciones.setLayout(PanelOperacionesLayout);
        PanelOperacionesLayout.setHorizontalGroup(
            PanelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOperacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnCalcularMapa, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelOperacionesLayout.setVerticalGroup(
            PanelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelOperacionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnCalcularMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelMapa.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        PanelMapa.setAutoscrolls(true);

        javax.swing.GroupLayout PanelMapaLayout = new javax.swing.GroupLayout(PanelMapa);
        PanelMapa.setLayout(PanelMapaLayout);
        PanelMapaLayout.setHorizontalGroup(
            PanelMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );
        PanelMapaLayout.setVerticalGroup(
            PanelMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        ScrollMapa.setViewportView(PanelMapa);

        MenuAbrir.setText("Archivo");

        ItemAbrir.setText("Abrir...");
        ItemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemAbrirActionPerformed(evt);
            }
        });
        MenuAbrir.add(ItemAbrir);

        BarraMenus.add(MenuAbrir);

        MenuEditar.setText("Editar");
        BarraMenus.add(MenuEditar);

        setJMenuBar(BarraMenus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ScrollMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ScrollMapa)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemAbrirActionPerformed
        int seleccionArchivo = SelectorArchivo.showOpenDialog(VentanaSeleccionarArchivo);
        
        // Al cargar el archivo, leer mapa
        if (seleccionArchivo == JFileChooser.APPROVE_OPTION) {
            // Obtener archivo
            File archivo = SelectorArchivo.getSelectedFile();
            
            // Leer mapa
            try {
                LectorArchivosXML lector = new LectorArchivosXML();
                int[][] mapa = lector.leerMapa(archivo);
                
                // Mostrar el mapa en el panel de mapa
                PanelMapa.setLayout(new GridLayout(mapa.length, mapa[0].length, 0, 0));
                for (int i = 0; i < mapa.length; i++) {
                    for (int j = 0; j < mapa[0].length; j++) {
                        JLabel celda = new JLabel("" + mapa[i][j], SwingConstants.CENTER);
                        celda.setBorder(BorderFactory.createLineBorder(Color.BLACK));
                        PanelMapa.add(celda);
                    }
                }
                
                PanelMapa.revalidate();
                PanelMapa.repaint();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, 
                    "Error al leer el archivo: " + e.getMessage(),
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_ItemAbrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenus;
    private javax.swing.JButton BtnCalcularMapa;
    private javax.swing.JMenuItem ItemAbrir;
    private javax.swing.JMenu MenuAbrir;
    private javax.swing.JMenu MenuEditar;
    private javax.swing.JPanel PanelMapa;
    private javax.swing.JPanel PanelOperaciones;
    private javax.swing.JScrollPane ScrollMapa;
    private javax.swing.JFileChooser SelectorArchivo;
    private javax.swing.JDialog VentanaSeleccionarArchivo;
    // End of variables declaration//GEN-END:variables
}
